### ISSUE TITLE
Use link to our fork and text "Sharif Judge 1.5"

### ISSUE THREAD

**Issue by levysiqueira** [PCS-Poli-USP/Sharif-Judge#56]
Use the new version & link in the page (bottom of the menu)
![image](https://user-images.githubusercontent.com/1347668/42590209-8f9c30de-8519-11e8-9421-d7abe0df5a46.png)

**Comment by rrrahal** [comment]
fixed on 0fe1dc96161dcd42c77c31174aa8f5ccc8ae48d7
