### ISSUE TITLE
Color of status is green even if it is not 100% when status is updated automatically

### ISSUE THREAD

**Issue by levysiqueira** [PCS-Poli-USP/Sharif-Judge#68]
Isso acontece com a atualização automática do status.

![image](https://user-images.githubusercontent.com/1347668/43343883-46a156d2-91be-11e8-8367-136d34687a67.png)

**Comment by rrrahal** [comment]
fixed on c9bcc1859eed7ab1fd7875a0c6b2dcbd166f82d8
