### ISSUE TITLE
If Weight is changed in assignment, the weight for the student should be updated

### ISSUE THREAD

**Issue by levysiqueira** [PCS-Poli-USP/Sharif-Judge#75]
O ideal seria não ter a coluna "weight" na tabela "submission" (onde estão as submissões dos alunos). Isso deveria ser pego na tabela "problem" (onde está o cadastro do problema).

**Comment by rrrahal** [comment]
fixed on cd238f575b91c7ed1e44f816c61f88f8a6301f1e and 41908866b8d7a2d356789861dd6bffc363bae7f2
